# login route as the default route
//log as admin
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"admin1",
    "password":"adminpassword"
}

###
POST http://localhost:3000/admin/registerHost
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTg4MzllNTVjYTYxMTNhNzE1MGRkN2MiLCJjYXRlZ29yeSI6ImFkbWluIiwiaWF0IjoxNzAzNDI3NDAwLCJleHAiOjE3MDM0MzEwMDB9.Z2jpvUgmufGV2-84SSUmp2GhvggwpSDjeh7q_Vvtnsc
Content-Type: application/json

{
    "username":"yc1",
    "password":"12345",
    "email":"gg@gmail.com",
    "phoneNumber":"123456789"
}

###
GET http://localhost:3000/admin/visits
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NThhNTI4MzNmZWI5MmIxOTEwMWRmNTEiLCJjYXRlZ29yeSI6ImFkbWluIiwiaWF0IjoxNzAzNTYzOTQ4LCJleHAiOjE3MDM1Njc1NDh9.8dyzMCuGe8RUQSCGSWrohRWP9fjYWYuzx20k_kRL9gk
Content-Type: application/json


//login with host 1
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "host1",
    "password": "hostpassword"
}

###
GET http://localhost:3000/host/65870f9625c971ef6ae3d912
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTg3MGY5NjI1Yzk3MWVmNmFlM2Q5MTIiLCJjYXRlZ29yeSI6Imhvc3QiLCJpYXQiOjE3MDMzNTQwMzgsImV4cCI6MTcwMzM1NzYzOH0.P9gbR9Wmc73l59vIFcBWQNB1abqWwyECtcq1Q5kYNd0
Content-Type: application/json

###
GET http://localhost:3000/host/65870f9625c971ef6ae3d912/visitors
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTg3MGY5NjI1Yzk3MWVmNmFlM2Q5MTIiLCJjYXRlZ29yeSI6Imhvc3QiLCJpYXQiOjE3MDMzNTQwMzgsImV4cCI6MTcwMzM1NzYzOH0.P9gbR9Wmc73l59vIFcBWQNB1abqWwyECtcq1Q5kYNd0
Content-Type: application/json



